/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:84be73a0-a7ec-47f2-bb80-3d8710e528f3",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_Vl2eiX8Cz",
    "aws_user_pools_web_client_id": "3kpe00ckpl87ivi9un2perj5v5"
};


export default awsmobile;
